### PR TITLE
Update links & add support for 0.18

### PR DESCRIPTION
**Pull request by Joery**
- Update link to Factorio wiki page
- Update link to Factorio website
- Add support for 0.18
- Bump version to 0.1.4

### CODE REVIEW

**Comment by Cerbrus** [comment]
Thanks for looking into this, @Joery. Did you test if the plugin works with the version number updated? I'll be able to check tomorrow.

**Comment by jonfairbanks** [comment]
Hey @Cerbrus, any chance of getting this merged? Thank you! 😄

**Comment by Cerbrus** [comment]
I've merged the changes and updated the mod at https://mods.factorio.com/mod/TogglePeacefulMode

Would you be willing to verify the update works, @jonfairbanks / @Joery? I'm currently not in a situation where I'm able to start Factorio.

**Comment by jonfairbanks** [comment]
Working good. Thanks!

**Comment by Cerbrus** [comment]
Excellent! Thanks for checking :-)

**Pull request merged**
