### PR TITLE
Optimized redundant force lookup in tpm.reset_biters(). 

### PR DESCRIPTION
**Pull request by Higgs1**
I did a thing :D. I dunno if it's a thingy you like, but I did it.

### CODE REVIEW

**Comment by Cerbrus** [comment]
Hm, yea, that's cleaner!

There's also apparently a bug with the migration you added:
https://github.com/Cerbrus/FactorioMods-TogglePeacefulMode/issues/7

Do you happen to know how to fix that? :D

**Comment by ssanderlin** [comment]
FWIW, I'm not familiar with factorio modding or Lua at all but it seems like the mod is adding the button as part of being activated and then the migration, which I'm assuming is run during a sync to a save, is trying to add it again. Seems like a check in the init method to see if the button already exists prior to attempting to add would fix the issue, or modifying the init method to remove and re-add it.

**Comment by Higgs1** [comment]
Oops, my bad! I'm pretty sure I fixed it. This issue only occurs when a save is created without any version of TPM installed, and then is loaded with TPM >= 0.3, because then both the init script, and also the migration script would run. This doesn't happen when a save with an older version of TPM is loaded, because only the migration script is executed; or with new saves where only the init script runs. @ssanderlin's idea worked perfectly, thank you :D

**Comment by ssanderlin** [comment]
@Higgs1 Happy to help!

**Comment by Cerbrus** [comment]
I've verified the fix on a new world, and it appears to work!

Thanks for the input!

**Pull request merged**
